//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use chrono::Utc;
use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "images")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    pub score: i32,
    #[serde(with = "chrono::serde::ts_seconds")]
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip)]
    pub deleted_at: Option<chrono::DateTime<chrono::Utc>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub display_name: Option<String>,
    #[serde(skip)]
    pub room_id: Uuid,
    #[serde(skip)]
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub object_key: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::image_vote::Entity")]
    ImageVote,
    #[sea_orm(
        belongs_to = "super::room::Entity",
        from = "Column::RoomId",
        to = "super::room::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Room,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
}

impl Related<super::image_vote::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImageVote.def()
    }
}

impl Related<super::room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Room.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::image_vote::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::image_vote::Relation::Images.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
